map_name: oven_of_witch

vqvae_path: model_params/vqvae_ep30.pth
rssm_path: model_params/rssm_ep150.pth

combined_path: oow_combined_data.npz
is_train: false
device: cpu 

observation_shape: [3, 128, 256] # (Channels, Height, Width)
action_size: 3 # (none, jump, slide)

gradient_norm_type: 2
gradient_clip: 100

#################### VQ-VAE hyperparameter ####################

vq_codebook_size: 256    
vq_code_dim: 8       
vq_commitment_cost: 0.25   
vq_ema_decay: 0.99       

vq_spatial_shape: [16, 32] 
vq_num_tokens: 512 # 16 * 32   

vqvae_train_epochs: 30
vqvae_lr: 0.0003
vqvae_batch_size: 64

perceptual_weight: 0.1 # for VGG loss 

#################### RSSM hyperparameter ####################

rssm_train_epochs: 200
rssm_lr: 0.0003

rssm_batch_size: 128
rssm_batch_length: 32

encoded_state_size: 1024
recurrent_size: 512
latent_length: 32
latent_classes: 32
latent_size: 1024 # latent_length * latent_classes

label_smoothing: 0.1 # for cross entropy loss
rssm_kl_weight: 0.01
uniform_mix: 0.01
posterior_coefficient: 0.1
prior_coefficient: 1.0
free_nat: 1 # I consider it unnecessary