map_name: oven_of_witch

vae_path: model_params/vae_ep30.pth
rssm_path: model_params/rssm_ep300.pth

combined_path: oow_combined_data.npz
is_train: false

observation_shape: [3, 128, 256] # (Channels, Height, Width)
action_size: 3 # (none, jump, slide)

device: cpu 
latent_channel: 4
latent_shape_vae: [4, 16, 32]

gradient_norm_type: 2
gradient_clip: 100

#################### VAE hyperparameter ####################

vae_train_epochs: 30
vae_lr: 0.0003
vae_kl_weight: 0.000001

vae_batch_size: 64

#################### RSSM hyperparameter ####################

rssm_train_epochs: 100
rssm_lr: 0.0003

rssm_batch_size: 200
rssm_batch_length: 50

encoded_state_size: 1024
recurrent_size: 512
latent_length: 16
latent_classes: 16
latent_size: latent_length * latent_classes

uniform_mix: 0.01
posterior_coefficient: 0.1
prior_coefficient: 0.5
free_nat: 1