map_name: oven_of_witch

vqvae_path: model_params/vqvae_ep30.pth
rssm_path: model_params/rssm_ep400.pth

combined_path: oow_combined_data.npz
is_train: false
device: cpu 

observation_shape: [3, 128, 256] # (Channels, Height, Width)
action_size: 3 # (none, jump, slide)

gradient_norm_type: 2
gradient_clip: 100

video_fps: 24

#################### FSQ VQ-VAE hyperparameter ####################

fsq_levels: [4, 4, 4]
fsq_code_dim: 3       # len(fsq_levels), D = 3
fsq_codebook_size: 64 # K = 64 

fsq_spatial_shape: [8, 16] # (Height, Width)
fsq_num_tokens: 128 # H * W = 128

vqvae_train_epochs: 30
vqvae_lr: 0.001
vqvae_batch_size: 64

perceptual_weight: 0.3 # for VGG loss 

#################### RSSM hyperparameter ####################

rssm_train_epochs: 400
rssm_lr: 0.001

rssm_batch_size: 512
rssm_batch_length: 32

encoded_state_size: 512
recurrent_size: 512
latent_length: 32
latent_classes: 32
latent_size: 1024 # latent_length * latent_classes

label_smoothing: 0 # Not very helpful whether its 0.1 or 0.01.
rssm_kl_weight: 0.1
uniform_mix: 0.01
posterior_coefficient: 0.1
prior_coefficient: 1.0
free_nat: 1 # for preventing posterior collapse early in training.
